### ISSUE TITLE
Adding support to GCP

### ISSUE THREAD

**Issue by jesayafn** [vectra-ai-research/Halberd#30]
Let the support be wider to GCP.

**Comment by openrec0n** [comment]
Hi @jesayafn , GCP is definitely in works for future coverage. Feel to add ideas for GCP techniques in [discussions here](https://github.com/vectra-ai-research/Halberd/discussions/23)

**Comment by jesayafn** [comment]
Hi @openrec0n. I created a branch on my fork to add support for GCP. Could you make a separate branch, or can I go directly to the main branch?

See https://github.com/vectra-ai-research/Halberd/compare/main...jesayafn:dev/gcp?expand=1
